# https://www.mkdocs.org/user-guide/configuration/
site_name: Basis for Deep Learning with PyTorch
site_url: null
repo_url: 
docs_dir: source
site_dir: site
nav:
    - Home: index.md
    - About: about.md
theme: material # readthedocs
